import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";

export class MemoryRegistry {
  #db: DatabaseSync | undefined;
  constructor(readonly path: string) {}
  open(): void { this.#db = new DatabaseSync(this.path); this.#db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS memory_candidates_v1 (id TEXT PRIMARY KEY, source TEXT NOT NULL, candidate TEXT NOT NULL, status TEXT NOT NULL, correction TEXT, created_at TEXT NOT NULL, confirmed_at TEXT, deleted_at TEXT) STRICT;"); }
  close(): void { this.#db?.close(); this.#db = undefined; }
  add(source: string, candidate: string): string { requireText(source,"source",256); requireText(candidate,"candidate",4096); const id=randomBytes(16).toString("hex"), now=new Date().toISOString(); this.db.prepare("INSERT INTO memory_candidates_v1 VALUES (?, ?, ?, 'PENDING', NULL, ?, NULL, NULL)").run(id,source,candidate,now); return id; }
  confirm(id: string, correction?: string): void { requireId(id); if(correction!==undefined) requireText(correction,"correction",4096); const result=this.db.prepare("UPDATE memory_candidates_v1 SET status='CONFIRMED', correction=?, confirmed_at=? WHERE id=? AND status='PENDING' AND deleted_at IS NULL").run(correction??null,new Date().toISOString(),id); if (result.changes !== 1) throw new Error("Memory candidate is not confirmable"); }
  remove(id: string): void { requireId(id); this.db.prepare("UPDATE memory_candidates_v1 SET status='DELETED', deleted_at=? WHERE id=? AND deleted_at IS NULL").run(new Date().toISOString(),id); }
  exportConfirmed(): readonly {id:string;value:string;source:string}[] { return this.db.prepare("SELECT id, COALESCE(correction,candidate) AS value, source FROM memory_candidates_v1 WHERE status='CONFIRMED' AND deleted_at IS NULL").all() as {id:string;value:string;source:string}[]; }
  get db(): DatabaseSync { const db=this.#db; if(db===undefined) throw new Error("Memory registry is not open"); return db; }
}

/** Gateway credentials are per-channel ingest secrets, never Owner credentials. */
export class ChannelIngestRegistry {
  #db: DatabaseSync | undefined;
  constructor(readonly path: string) {}
  open(): void { this.#db=new DatabaseSync(this.path); this.#db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS channel_ingest_v1 (channel TEXT PRIMARY KEY, token_hash TEXT NOT NULL, paired_sender TEXT, updated_at TEXT NOT NULL) STRICT; CREATE TABLE IF NOT EXISTS channel_replay_v1 (channel TEXT NOT NULL, message_id TEXT NOT NULL, received_at TEXT NOT NULL, PRIMARY KEY(channel,message_id)) STRICT;"); }
  close(): void {this.#db?.close();this.#db=undefined;}
  rotate(channel:string):string { requireChannel(channel); const token=randomBytes(32).toString("base64url");this.db.prepare("INSERT INTO channel_ingest_v1 VALUES(?,?,NULL,?) ON CONFLICT(channel) DO UPDATE SET token_hash=excluded.token_hash,paired_sender=NULL,updated_at=excluded.updated_at").run(channel,hash(token),new Date().toISOString());return token; }
  pair(channel:string,sender:string):void {requireChannel(channel);requireText(sender,"sender",256);const result=this.db.prepare("UPDATE channel_ingest_v1 SET paired_sender=?,updated_at=? WHERE channel=?").run(sender,new Date().toISOString(),channel);if(result.changes!==1)throw new Error("Channel has no ingest credential");}
  accept(channel:string,token:string,sender:string,messageId:string,isGroup:boolean):boolean {try{requireChannel(channel);requireText(sender,"sender",256);requireId(messageId);if(!/^[A-Za-z0-9_-]{43}$/.test(token))return false;}catch{return false;}const r=this.db.prepare("SELECT token_hash AS h,paired_sender AS s FROM channel_ingest_v1 WHERE channel=?").get(channel) as {h:string;s:string|null}|undefined;if(!r||isGroup||r.s!==sender||!same(r.h,hash(token)))return false;try{this.db.prepare("INSERT INTO channel_replay_v1 VALUES(?,?,?)").run(channel,messageId,new Date().toISOString());return true;}catch{return false;} }
  get db():DatabaseSync {const db=this.#db;if(db===undefined)throw new Error("Gateway registry is not open");return db;}
}
export function mediaExpiry(expiresAt:string):boolean{return Number.isFinite(Date.parse(expiresAt))&&Date.parse(expiresAt)>Date.now();}
export interface VoiceProviderConfig { readonly baseUrl: URL; readonly sttModel: string; readonly ttsModel: string; readonly apiKey: string; }
/** Voice stays disabled unless all three private values are present and the provider is HTTPS/loopback. */
export function loadVoiceProviderConfig(env: NodeJS.ProcessEnv=process.env): VoiceProviderConfig|undefined {const values=[env.FRIDAY_VOICE_BASE_URL,env.FRIDAY_STT_MODEL,env.FRIDAY_TTS_MODEL,env.FRIDAY_VOICE_API_KEY];if(values.every(v=>v===undefined||v===""))return undefined;if(values.some(v=>typeof v!=="string"||v.trim()===""))throw new Error("Voice configuration must be complete");let baseUrl:URL;try{baseUrl=new URL(env.FRIDAY_VOICE_BASE_URL as string);}catch{throw new Error("FRIDAY_VOICE_BASE_URL must be an absolute URL");}const config={baseUrl,sttModel:env.FRIDAY_STT_MODEL as string,ttsModel:env.FRIDAY_TTS_MODEL as string,apiKey:env.FRIDAY_VOICE_API_KEY as string};validateVoiceProviderConfig(config);return config;}
export function validateVoiceProviderConfig(config:VoiceProviderConfig):void {const loopback=config.baseUrl.hostname==="127.0.0.1"||config.baseUrl.hostname==="[::1]";if((config.baseUrl.protocol!=="https:"&&!loopback)||config.baseUrl.username!==""||config.baseUrl.password!=="")throw new Error("FRIDAY_VOICE_BASE_URL must be HTTPS or loopback");requireText(config.sttModel,"STT model",256);requireText(config.ttsModel,"TTS model",256);if(config.apiKey.length<16||config.apiKey.length>1024||/\s/.test(config.apiKey))throw new Error("Voice API key is invalid");}

export interface VoiceMedia { readonly id:string; readonly mimeType:string; readonly sizeBytes:number; readonly sha256:string; readonly expiresAt:string; }
interface StoredVoiceMedia extends VoiceMedia { readonly path:string; }
/** Media is short-lived, private and addressable only by random opaque IDs. */
export class VoiceMediaRegistry {
  #db:DatabaseSync|undefined;
  readonly #directory:string;
  constructor(readonly databasePath:string,directory:string){this.#directory=resolve(directory);}
  open():void{mkdirSync(this.#directory,{recursive:true,mode:0o700});this.#db=new DatabaseSync(this.databasePath);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS voice_media_v1 (id TEXT PRIMARY KEY,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,sha256 TEXT NOT NULL,path TEXT NOT NULL,expires_at TEXT NOT NULL,deleted_at TEXT) STRICT;");this.expire();}
  close():void{this.#db?.close();this.#db=undefined;}
  save(bytes:Uint8Array,mimeType:string,ttlSeconds=900):VoiceMedia{if(!/^audio\/[a-z0-9.+-]{1,127}$/i.test(mimeType)||bytes.byteLength<1||bytes.byteLength>8*1024*1024||!Number.isSafeInteger(ttlSeconds)||ttlSeconds<30||ttlSeconds>86_400)throw new Error("Voice media is invalid");const id=randomBytes(16).toString("hex"),path=join(this.#directory,`${id}.bin`),expiresAt=new Date(Date.now()+ttlSeconds*1000).toISOString(),sha256=createHash("sha256").update(bytes).digest("hex");writeFileSync(path,bytes,{flag:"wx",mode:0o600});try{this.db.prepare("INSERT INTO voice_media_v1 VALUES(?,?,?,?,?,?,NULL)").run(id,mimeType,bytes.byteLength,sha256,path,expiresAt);}catch(error){try{unlinkSync(path);}catch{}throw error;}return{id,mimeType,sizeBytes:bytes.byteLength,sha256,expiresAt};}
  read(id:string):{readonly media:VoiceMedia;readonly bytes:Buffer}|undefined{const stored=this.#stored(id);if(stored===undefined)return undefined;try{return{media:stripPath(stored),bytes:readFileSync(stored.path)}}catch{return undefined;}}
  remove(id:string):void{const stored=this.#stored(id);if(stored===undefined)return;this.db.prepare("UPDATE voice_media_v1 SET deleted_at=? WHERE id=? AND deleted_at IS NULL").run(new Date().toISOString(),id);try{unlinkSync(stored.path);}catch{}}
  expire(now=Date.now()):number{const rows=this.db.prepare("SELECT id,mime_type AS mimeType,size_bytes AS sizeBytes,sha256,path,expires_at AS expiresAt FROM voice_media_v1 WHERE deleted_at IS NULL AND expires_at<=?").all(new Date(now).toISOString()) as unknown as StoredVoiceMedia[];for(const row of rows)this.remove(row.id);return rows.length;}
  #stored(id:string):StoredVoiceMedia|undefined{if(!/^[a-f0-9]{32}$/.test(id))return undefined;const row=this.db.prepare("SELECT id,mime_type AS mimeType,size_bytes AS sizeBytes,sha256,path,expires_at AS expiresAt FROM voice_media_v1 WHERE id=? AND deleted_at IS NULL").get(id) as StoredVoiceMedia|undefined;if(row===undefined)return undefined;if(Date.parse(row.expiresAt)<=Date.now()){this.remove(id);return undefined;}return row;}
  get db():DatabaseSync{if(this.#db===undefined)throw new Error("Voice media registry is not open");return this.#db;}
}
export class OpenAiVoiceClient {
  constructor(readonly config:VoiceProviderConfig){}
  async transcribe(media:{readonly mimeType:string;readonly bytes:Buffer}):Promise<string>{const body=new FormData();body.set("model",this.config.sttModel);const fileBytes=new Uint8Array(media.bytes.byteLength);fileBytes.set(media.bytes);body.set("file",new Blob([fileBytes.buffer],{type:media.mimeType}),"voice.bin");const response=await fetch(new URL("audio/transcriptions",this.config.baseUrl),{method:"POST",redirect:"error",headers:{authorization:`Bearer ${this.config.apiKey}`},body,signal:AbortSignal.timeout(60_000)});if(!response.ok)throw new Error("Voice transcription provider rejected the request");const value=await response.json() as {text?:unknown};if(typeof value.text!=="string"||value.text.trim()===""||value.text.length>32_768)throw new Error("Voice transcription provider returned invalid text");return value.text;}
  async synthesize(text:string,voice="alloy"):Promise<{readonly mimeType:string;readonly bytes:Buffer}>{requireText(text,"TTS text",16_384);if(!/^[a-z0-9_-]{1,64}$/i.test(voice))throw new Error("TTS voice is invalid");const response=await fetch(new URL("audio/speech",this.config.baseUrl),{method:"POST",redirect:"error",headers:{authorization:`Bearer ${this.config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:this.config.ttsModel,input:text,voice,format:"mp3"}),signal:AbortSignal.timeout(60_000)});if(!response.ok)throw new Error("Voice synthesis provider rejected the request");const bytes=Buffer.from(await response.arrayBuffer());if(bytes.byteLength<1||bytes.byteLength>8*1024*1024)throw new Error("Voice synthesis provider returned invalid media");const contentType=response.headers.get("content-type")?.split(";",1)[0]??"audio/mpeg";if(!/^audio\//.test(contentType))throw new Error("Voice synthesis provider returned invalid media type");return{mimeType:contentType,bytes};}
}
function stripPath(value:StoredVoiceMedia):VoiceMedia{return{id:value.id,mimeType:value.mimeType,sizeBytes:value.sizeBytes,sha256:value.sha256,expiresAt:value.expiresAt};}
function requireChannel(value:string):void {if(value!=="telegram"&&value!=="wechat_ilink")throw new Error("Unsupported channel");} function requireId(value:string):void {if(!/^[a-f0-9]{32}$/i.test(value)&&! /^[0-9a-f]{8}-/i.test(value))throw new Error("Invalid id");} function requireText(value:string,name:string,max:number):void {if(typeof value!=="string"||value.trim()===""||value.length>max)throw new Error(`Invalid ${name}`);}
function hash(s:string){return createHash("sha256").update(s).digest("hex");}function same(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
